markets:
  - 'BINANCE:SOL/USDT'
  - 'BINANCE:AVAX/USDT'
  - 'BINANCE:LINK/USDT'
  - 'BINANCE:MATIC/USDT'
  - 'BINANCE:XRP/USDT'
  - 'BINANCE:ADA/USDT'
  - 'BINANCE:DOT/USDT'
  - 'BINANCE:ARB/USDT'
  - 'BINANCE:OP/USDT'
  - 'BINANCE:INJ/USDT'
timeframes: ['3m', '5m', '15m', '1h', '4h', '12h', '1d']
start: '2021-01-01'
end: null
limit_per_call: 1000
