markets:
  - 'BINANCE:SOL/USDT'
  - 'BINANCE:AVAX/USDT'
  - 'BINANCE:LINK/USDT'
  - 'BINANCE:MATIC/USDT'
  - 'BINANCE:XRP/USDT'
  - 'BINANCE:ADA/USDT'
  - 'BINANCE:DOT/USDT'
  - 'BINANCE:ARB/USDT'
  - 'BINANCE:OP/USDT'
  - 'BINANCE:INJ/USDT'
timeframe: '1h'
start: '2021-01-01'
end: null
limit_per_call: 1000
